name: test
on:
  push:
    branches:
      # Change this if your primary branch is not main
      - master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v3
      - name: Test
        run: npx nx test sample-server